# Generated by Django 5.0 on 2023-12-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
