# Generated by Django 5.0 on 2023-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_questionset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
    ]
