# Generated by Django 5.0 on 2023-12-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_leaderboard_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='total_marks',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='marks',
            field=models.FloatField(default=0),
        ),
    ]
